// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "charmaine.kwok"
        },
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/movies/{type}": {
            "get": {
                "description": "Get a list of movie information by type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "summary": "Get a list of movie information by type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Type",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Page Number",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Movies Information",
                        "schema": {
                            "$ref": "#/definitions/controllers.MoviesInformationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid type"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/movies/{type}/details/{title}": {
            "get": {
                "description": "Get movie information by Title",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Movies"
                ],
                "summary": "Get movie information by Title",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Type",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Title",
                        "name": "title",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Movie Information",
                        "schema": {
                            "$ref": "#/definitions/controllers.MovieInformationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid type"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/non-movies": {
            "get": {
                "description": "Get a list of non-movies information by type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Non-movies"
                ],
                "summary": "Get a list of non-movies information by type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Page Number",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Information",
                        "schema": {
                            "$ref": "#/definitions/controllers.NonMovieListInformationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid type"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/non-movies/details/{title}": {
            "get": {
                "description": "Get non-movie information by Title",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Non-movies"
                ],
                "summary": "Get non-movie information by Title",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Title",
                        "name": "title",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Non-Movie Information",
                        "schema": {
                            "$ref": "#/definitions/controllers.NonMovieInformationResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid type"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.MovieInformationResponse": {
            "type": "object",
            "properties": {
                "item": {
                    "$ref": "#/definitions/models.Movie"
                }
            }
        },
        "controllers.MoviesInformationResponse": {
            "type": "object",
            "properties": {
                "currentPage": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Movie"
                    }
                },
                "totalItem": {
                    "type": "integer"
                },
                "totalPage": {
                    "type": "integer"
                }
            }
        },
        "controllers.NonMovieInformationResponse": {
            "type": "object",
            "properties": {
                "item": {
                    "$ref": "#/definitions/models.NonMovie"
                }
            }
        },
        "controllers.NonMovieListInformationResponse": {
            "type": "object",
            "properties": {
                "currentPage": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.NonMovie"
                    }
                },
                "totalItem": {
                    "type": "integer"
                },
                "totalPage": {
                    "type": "integer"
                }
            }
        },
        "models.Movie": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "pic": {
                    "type": "string"
                },
                "rating": {
                    "type": "string"
                },
                "title_en": {
                    "type": "string"
                },
                "title_zh": {
                    "type": "string"
                },
                "wiki_url": {
                    "type": "string"
                }
            }
        },
        "models.NonMovie": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "desc": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "pic": {
                    "type": "string"
                },
                "rating": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "go-crud.fly.dev/api",
	Schemes:          []string{},
	Title:            "Movie App",
	Description:      "This is an API server for communication between mobile application and MongoDB Database",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
